import Header from "@/components/header";
import Footer from "@/components/footer";

import { Metadata } from "next";
// import { ErrorWrapper } from "./error-wrapper";

export const metadata: Metadata = {
  title: {  // default is the default, template applies to children, absolute allows children to override the template
    default: "Next.js Tutorial - Codevolution",
    template: "%s | Codevolution",
  },
  description: "Generated by Next.js",
};

// you can use a completely new layout for each route group if you don't define a root layout like this one

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}